version: '3.8'

secrets:
  mongo_root_password:
    file: ./secrets/mongo_root_password.txt
  neo4j_password:
    file: ./secrets/neo4j_password.txt
  minio_password:
    file: ./secrets/minio_password.txt

services:
  # MongoDB - Perfiles de usuarios, metadatos de contenidos, interacciones
  mongodb:
    image: mongo:7.0
    container_name: comuniarte-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_root_password
      MONGO_INITDB_DATABASE: comuniarte_db
    secrets:
      - mongo_root_password
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - comuniarte-network
    command: mongod --auth

  # Neo4j - Grafo de creadores/seguidores y recomendaciones
  neo4j:
    image: neo4j:5.15-community
    container_name: comuniarte-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      NEO4J_AUTH: neo4j/admin1234
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_security_procedures_allowlist: apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - comuniarte-network

  # Redis - Chat en vivo, contadores, eventos en tiempo real
  redis:
    image: redis:7.2-alpine
    container_name: comuniarte-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - comuniarte-network
    command: redis-server /usr/local/etc/redis/redis.conf

  # MinIO - Almacenamiento S3-compatible para videos y audios
  minio:
    image: minio/minio:latest
    container_name: comuniarte-minio
    restart: unless-stopped
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin1234
    volumes:
      - minio_data:/data
    networks:
      - comuniarte-network
    command: server /data --console-address ":9001"

  # Redis Commander - Interfaz web para Redis (opcional, para desarrollo)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: comuniarte-redis-commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379
    networks:
      - comuniarte-network
    depends_on:
      - redis

  # Nginx Reverse Proxy (desarrollo)
  nginx:
    image: nginx:alpine
    container_name: comuniarte-nginx
    restart: unless-stopped
    ports:
      - "80:80"   # HTTP
    volumes:
      - ./config/nginx-dev.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - comuniarte-network
    depends_on:
      - mongodb
      - neo4j
      - redis
      - minio
      - redis-commander

volumes:
  mongodb_data:
    driver: local
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local

networks:
  comuniarte-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
